### PR TITLE
Add `on_warning` to `dbtcloud_notification` and `dbtcloud_partial_notification`

### PR DESCRIPTION
**Pull request by chasewalden**

### CODE REVIEW

**Comment by chasewalden** [comment]
Acceptance Tests pending

**Comment by b-per** [comment]
Thanks @chasewalden !

At the same time that you add/modify acceptance tests, could you also update the CHANGELOG to mention what was changed?

Once done, I can approve it and we can do a new release.

**Comment by chasewalden** [comment]
@b-per, Acceptance Tests added and CHANGELOG updated. Not sure if I've done the latter correctly, so please lmk if I missed something.

Should be ready to go once CI finishes

**Review by b-per — APPROVED** [review]

**Comment by b-per** [comment]
Thanks @chasewalden 
I will do another PR to update the examples of the the resources I modified before and to do a new release of the provider

**Pull request merged**
