### PR TITLE
feat: License Map Resource

### PR DESCRIPTION
**Pull request by SudoSpartanDan**
This PR adds the ability to create/manage license maps within DBT Cloud.

### CODE REVIEW

**Comment by SudoSpartanDan** [comment]
I seem to be having issues with the license type already existing in the acceptance test instance. Any possibility to look into the instance to see if a previous test was not cleaned up?

**Comment by b-per** [comment]
There was one dangling mapping for the Developer license. I just removed it.

**Comment by SudoSpartanDan** [comment]
> There was one dangling mapping for the Developer license. I just removed it.

That did it, this PR is ready for review @b-per

**Comment by b-per** [comment]
Thanks a lot for getting it passing and for having an Acceptance Test!

I have created #179 to add some minor changes on top of your commits (I don't have access to push to your repo).
- As the list of SSO groups is not ordered and should contain unique groups, it is more akin to a set than a list
- I have updated the test to check when we are assigning multiple groups

So, when CI passes for #179 I will merge it and close this one

I will update the README and do a new release today as well

**Comment by SudoSpartanDan** [comment]
> 

Sounds great, thank you!

**Pull request merged**
